HeThongQuanLyBanVeMayBay/Controllers/AdminChiTietDonDatVeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HeThongQuanLyBanVeMayBay.Models;

namespace HeThongQuanLyBanVeMayBay.Controllers
{
    public class AdminChiTietDonDatVeController : Controller
    {
        private HTQLBVMBver1 db = new HTQLBVMBver1();

        // GET: AdminChiTietDonDatVe
        public ActionResult Index()
        {
            if (SESSION.MaGp.Equals("Admin") || SESSION.MaGp.Equals("Nhân viên bán vé"))
            {
                var cT_DDV = db.CT_DDV.Include(c => c.DONDATVE).Include(c => c.VE);
                return View(cT_DDV.ToList());
            }
            else
            {
                TempData["CanhBao1"] = "Xin lỗi !! bạn không được cấp quyền vào mục này !!!";
                return RedirectToAction("TrangChuAdmin", "Admin");
            }
        }

        public ActionResult ChuyenDonHang(int? DonHangID)
        {
            if (SESSION.MaGp.Equals("Admin") || SESSION.MaGp.Equals("Nhân viên bán vé"))
            {
                if (DonHangID == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                CT_DDV ctddv = db.CT_DDV.SingleOrDefault(n => n.MaDDV == DonHangID);
                if (ctddv == null)
                {
                    return HttpNotFound();
                }
                var ldh = db.CT_DDV.Include(n => n.DONDATVE);
                ldh = ldh.Where(m => m.MaDDV == DonHangID);
                VE ve = db.VEs.SingleOrDefault(n => n.MaVe == ctddv.MaVe);

                if (ve.SoLuong <= 0)
                {
                    TempData["BaoLoi"] = "Không đủ số lượng vé, hãy liên lạc và thông báo cho khách hàng";
                    return RedirectToAction("Index");
                }
                else
                {
                    ctddv.DaThanhToan = 1;
                    ve.SoLuong = ve.SoLuong - ctddv.SoLuongDat;
                    TempData["ThanhCong"] = "Đã duyệt và thanh toán thành công !!";
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["CanhBao2"] = "Xin lỗi !! bạn không được cấp quyền vào mục này !!!";
                return RedirectToAction("TrangChuAdmin", "Admin");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeThongQuanLyBanVeMayBay/Views/AdminChiTietDonDatVe/Index.cshtml
@model IEnumerable<HeThongQuanLyBanVeMayBay.Models.CT_DDV>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}
<div class="main-agile banner-2">
</div>
<div class="banner-bottom" style="font-family:Arial">
    <h2 style="font-family:Arial">Chi tiết đơn đặt vé</h2>

    <h1 style="font-family:Arial;font-weight:bold;color:red"> @TempData["BaoLoi"] @TempData["ThanhCong"] @TempData["CanhBao1"] @TempData["CanhBao2"]</h1>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DONDATVE.MaDDV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VE.MaChuyenBay)
            </th>
            <th>
                Giá mỗi vé
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuongDat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DaThanhToan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeleteFlag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeleteTime)
            </th>
            <th>

            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaDDV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VE.MaChuyenBay)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.GiaVe)*@
                    @string.Format("{0:0,0}", item.GiaVe) VNĐ
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuongDat)
                </td>
                @if (item.DaThanhToan == 0)
                {
                    <td>
                        @Html.DisplayName("Chưa thanh toán")
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayName("Đã thanh toán")
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.DeleteFlag)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeleteTime)
                </td>
                <td>
                    @if (item.DaThanhToan == 0)
                    {
                        <a href=@Url.Action("ChuyenDonHang", "AdminChiTietDonDatVe", new { DonHangID = item.MaDDV })>Thanh toán</a>
                    }
                </td>
            </tr>
        }

    </table>
</div>